server:
  port: 9001

eureka:
  instance:
    hostname: eureka-server-01
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:9002/eureka