eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8790
spring:
  application:
    name: eureka-hystrix-turbine
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-ribbon,eureka-feign
  clusterNameExpression: new String("default")