server:
  port: 9002

eureka:
  instance:
    hostname: eureka-server-02
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://localhost:9001/eureka